package gui;

/**
 *
 * @author mathe
 */
public class PanelMensagens extends javax.swing.JPanel {

    /**
     * Creates new form PanelMensagens
     */
    public PanelMensagens() {
        initComponents();
    }
    
    /**
     * Função responsável por setar a label de mensagem com a String passada como parâmetro
     * @param mensagem 
     */
    public static void setLblMensagem(String mensagem) {
        lblMensagem.setText(mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblMensagem.setBackground(new java.awt.Color(255, 255, 255));
        lblMensagem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("Aguardando conexão do Player 2...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables
}
